version: "3.8"

services:
  mysqldb:
    container_name: mysql-db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: Uday@123
      MYSQL_DATABASE: airline_db
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    container_name: springboot
    build:
      context: ./BACKEND/airlinemanagement    # ✅ correct
      dockerfile: backend.Dockerfile          # ✅ relative to the context folder
    ports:
      - "2025:2004"                           # ✅ match EXPOSE in Dockerfile
    depends_on:
      - mysqldb
    restart: on-failure

  frontend:
    container_name: react
    build:
      context: ./frontendapp
      dockerfile: frontend.Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql-data:
